version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: projectdb
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-please-use-at-least-32-characters
      JWT_EXPIRES_IN: 24h
      NODE_ENV: development
    depends_on:
      - db
volumes:
  pgdata:
